### ISSUE TITLE
Follow requests 

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon-android#809]
I see that there is an icon that appears on the web app when a "follow request" comes in but I don't see that alert on the main app.
Should there be one?

**Comment by joenepraat** [comment]
This should be a priority #1 bug. There's still no possibility to accept or decline a follow request in this official app. An user today thought that their Mastodon account was broken.

**Comment by tenebrios** [comment]
> This should be a **priority 1 bug**. There's still no possibility to accept or decline a follow request in this official app. An user today thought that their Mastodon account was broken.

There's quite a few...a lot of difference between the web app and official app.
Hopefully they become more similar.

The lists feature is another thing I don't see on the official app

**Comment by grishka** [comment]
> The lists feature is another thing I don't see on the official app

Maybe try looking closer?

![Screenshot_20240817-091758.png](https://github.com/user-attachments/assets/9d5e9442-2ad1-4606-88fe-c9f0476b904a)

**Comment by tenebrios** [comment]
> > The lists feature is another thing I don't see on the official app
> 
> Maybe try looking closer?
> 
> ![Screenshot_20240817-091758.png](https://private-user-images.githubusercontent.com/1478258/358815835-9d5e9442-2ad1-4606-88fe-c9f0476b904a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MjEwOTMsIm5iZiI6MTcyMzkyMDc5MywicGF0aCI6Ii8xNDc4MjU4LzM1ODgxNTgzNS05ZDVlOTQ0Mi0yYWQxLTQ2MDYtODhmZS1jOWYwNDc2YjkwNGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMTg1MzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTMwZDRhMjYyODRiNzEyZDRhMzhmYjZiNTdkYWEzODUxMjU3N2Y4MmY1NjQ0ZmVmNDI2ZmJmOTI5ODQ3YTk0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HVa5yJNUoVtuqTyZx5bZTrXcO7eP0e9bsri4IJjuB1k)

Really no need for the witty/ sarcastic comment.
A simple it's under the home drop down would have been sufficient 👌🏻

**Comment by andypiper** [comment]
Answered above. Closing.

**Comment by joenepraat** [comment]
@andypiper This report was originally about the missing follow request notification. The list feature is indeed answered, but I don't see that the issue with missing follow request notification is resolved. Can you please re-open this issue?

**Comment by andypiper** [comment]
I apologise for my confusion!

**Comment by akno77** [comment]
I also have the problem that I get the notification for a new follower request but with no action ability to accept or decline the request .

I have found reports about this bug from posts more than 2 years ago! Unvelieviable that this is not fixed as it is a mandatory feature. This seems a good reason why new users don't use Mastodon ....
